use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

const LOCK_VERSION: u32 = 1;
const LOCK_HEADER: &str = "# Generated by `agt lock`. Commit this file; do not edit by hand.\n\n";

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Lockfile {
    pub version: u32,
    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LockedPackage {
    pub kind: String,
    pub name: String,
    /// `github:owner/repo`
    pub source: String,
    /// The rev the manifest asked for (branch, tag, or SHA) after defaulting.
    pub rev: String,
    pub commit: String,
    pub path: String,
    /// Git tree SHA of `path` at `commit` (gh's `github-tree-sha`).
    pub tree: String,
    /// Normalized content hash of the installed skill (see `integrity`).
    pub integrity: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub executables: Vec<String>,
}

impl LockedPackage {
    pub fn repo(&self) -> &str {
        self.source.strip_prefix("github:").unwrap_or(&self.source)
    }
}

impl Lockfile {
    pub fn new() -> Self {
        Self {
            version: LOCK_VERSION,
            packages: Vec::new(),
        }
    }

    pub fn load(path: &Path) -> Result<Option<Self>> {
        let content = match fs::read_to_string(path) {
            Ok(content) => content,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => return Err(e).with_context(|| format!("Failed to read {}", path.display())),
        };
        let lock: Self =
            toml::from_str(&content).with_context(|| format!("Invalid {}", path.display()))?;
        if lock.version != LOCK_VERSION {
            bail!(
                "{} has lock version {}, this agt understands {}",
                path.display(),
                lock.version,
                LOCK_VERSION
            );
        }
        Ok(Some(lock))
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let mut sorted = self.clone();
        sorted
            .packages
            .sort_by(|a, b| (&a.kind, &a.name).cmp(&(&b.kind, &b.name)));
        let body = toml::to_string(&sorted).context("Failed to serialize agt.lock")?;
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, format!("{LOCK_HEADER}{body}"))
            .with_context(|| format!("Failed to write {}", path.display()))
    }

    pub fn skill(&self, name: &str) -> Option<&LockedPackage> {
        self.packages
            .iter()
            .find(|p| p.kind == "skill" && p.name == name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_sorted() {
        let pkg = |name: &str| LockedPackage {
            kind: "skill".into(),
            name: name.into(),
            source: "github:a/b".into(),
            rev: "main".into(),
            commit: "c".repeat(40),
            path: format!("skills/{name}"),
            tree: "t".repeat(40),
            integrity: "agt1-sha256-x".into(),
            executables: vec!["run.sh".into()],
        };
        let mut lock = Lockfile::new();
        lock.packages = vec![pkg("zeta"), pkg("alpha")];
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("agt.lock");
        lock.save(&path).unwrap();
        let text = fs::read_to_string(&path).unwrap();
        assert!(text.find("alpha").unwrap() < text.find("zeta").unwrap());
        let loaded = Lockfile::load(&path).unwrap().unwrap();
        assert_eq!(loaded.skill("zeta").unwrap().repo(), "a/b");
        assert_eq!(loaded.packages.len(), 2);
    }

    #[test]
    fn rejects_future_version() {
        let tmp = tempfile::TempDir::new().unwrap();
        let path = tmp.path().join("agt.lock");
        fs::write(&path, "version = 9\n").unwrap();
        assert!(Lockfile::load(&path).is_err());
    }
}
